version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
      time: "13:00"
      timezone: "Australia/Brisbane"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Australia/Brisbane"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Australia/Brisbane"
